[build]
  functions = "functions"  # La carpeta donde están las funciones serverless
  publish = "public"       # La carpeta donde está el frontend

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/$1"
  status = 200