[build]
  functions = "functions"  # Carpeta donde están las serverless functions
  publish = "public"       # Carpeta donde está tu frontend (HTML/CSS/JS)

[functions]
  external_node_modules = ["express", "cors", "body-parser"]
